//! Account configuration loading and persistence.

use std::path::Path;

use rara_trading_engine::account_config::AccountsConfig;

/// Load accounts from the default path with environment variable overrides.
pub fn load_accounts() -> AccountsConfig {
    load_accounts_from_path(&crate::paths::accounts_file())
}

/// Load accounts from a specific path.
///
/// Falls back to empty config if the file does not exist.
/// Environment variables with prefix `RARA_ACCOUNTS` override file values.
pub fn load_accounts_from_path(path: &Path) -> AccountsConfig {
    // Parse TOML directly for correct serde handling of adjacently tagged
    // enums (BrokerConfig). The config crate's intermediate representation
    // loses the tag discrimination needed by `#[serde(tag, content)]`.
    if path.exists()
        && let Ok(contents) = std::fs::read_to_string(path)
        && let Ok(cfg) = toml::from_str::<AccountsConfig>(&contents)
    {
        return cfg;
    }

    // Fall back to config crate for env-only loading
    config::Config::builder()
        .add_source(config::Environment::with_prefix("RARA_ACCOUNTS").separator("_"))
        .build()
        .and_then(config::Config::try_deserialize)
        .unwrap_or_default()
}

/// Save accounts config to the default path.
pub fn save_accounts(cfg: &AccountsConfig) -> std::io::Result<()> {
    save_accounts_to_path(cfg, &crate::paths::accounts_file())
}

/// Save accounts config to a specific path.
pub fn save_accounts_to_path(cfg: &AccountsConfig, path: &Path) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let content = toml::to_string_pretty(cfg).expect("accounts serialization should not fail");
    std::fs::write(path, content)
}

/// Generate a commented accounts.toml template.
pub fn generate_accounts_template() -> String {
    r#"# rara-trading accounts configuration
# Generated by `rara setup init`
#
# Each [[accounts]] block defines a trading account.
# Sensitive fields (api_key, secret) can be overridden via environment variables:
#   RARA_ACCOUNTS_0_BROKER_CONFIG_API_KEY=...
#   RARA_ACCOUNTS_0_BROKER_CONFIG_SECRET=...

# ─── Example: Paper Trading Account ────────────────────────────
[[accounts]]
id = "paper-default"
label = "Paper Trading"
broker = "paper"
enabled = true
contracts = ["BTC-USDT"]

[accounts.broker_config]
fill_price = 50000.0

# ─── Example: Binance (uncomment to use) ───────────────────────
# [[accounts]]
# id = "binance-main"
# label = "Binance"
# broker = "ccxt"
# enabled = false
# contracts = ["BTC-USDT", "ETH-USDT"]
#
# [accounts.broker_config]
# exchange = "binance"
# sandbox = true
# api_key = ""
# secret = ""

# ─── Example: OKX (uncomment to use) ───────────────────────────
# [[accounts]]
# id = "okx-main"
# label = "OKX"
# broker = "ccxt"
# enabled = false
# contracts = ["BTC-USDT"]
#
# [accounts.broker_config]
# exchange = "okx"
# sandbox = true
# api_key = ""
# secret = ""
# passphrase = ""
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use std::io::Write;

    use tempfile::NamedTempFile;

    use super::*;

    #[test]
    fn load_from_toml_file() {
        let mut f = NamedTempFile::new().unwrap();
        write!(
            f,
            r#"
            [[accounts]]
            id = "paper-btc"
            broker = "paper"
            [accounts.broker_config]
            fill_price = 100.0
        "#
        )
        .unwrap();
        let cfg = load_accounts_from_path(f.path());
        assert_eq!(cfg.accounts.len(), 1);
        assert_eq!(cfg.accounts[0].id, "paper-btc");
    }

    #[test]
    fn load_missing_file_returns_empty() {
        let cfg = load_accounts_from_path(std::path::Path::new("/nonexistent/accounts.toml"));
        assert!(cfg.accounts.is_empty());
    }

    #[test]
    fn generate_template_is_valid_toml() {
        let template = generate_accounts_template();
        assert!(template.contains("[[accounts]]"));
        assert!(template.contains("broker"));
    }
}
